<div class="slider-wrapper theme-default">
    <div id="slider" class="nivoSlider">
        <img src="{$url_base}/uploads/slideshow/toystory.jpg" data-thumb="{$url_base}/uploads/slideshow/toystory.jpg" alt="" />
        <a href="http://dev7studios.com"><img src="{$url_base}/uploads/slideshow/up.jpg" data-thumb="{$url_base}/uploads/slideshow/up.jpg" alt="" title="This is an example of a caption" /></a>
        <img src="{$url_base}/uploads/slideshow/walle.jpg" data-thumb="{$url_base}/uploads/slideshow/walle.jpg" alt="" data-transition="slideInLeft" />
        <img src="{$url_base}/uploads/slideshow/nemo.jpg" data-thumb="{$url_base}/uploads/slideshow/nemo.jpg" alt="" title="#htmlcaption" />
    </div>
    <div id="htmlcaption" class="nivo-html-caption">
        <strong>This</strong> is an example of a <em>HTML</em> caption with <a href="#">a link</a>. 
    </div>
</div>
<script type="text/javascript">
    jQuery(window).load(function() {
        jQuery('#slider').nivoSlider();
    });
</script>
<div style="padding: 10px;">
    <div id="sidebar">
        <h3 class="categories-title">Categorias</h3>
        {product_category_list}
    </div>
    <div class="right-col">
        {product_list assign="products"}
        <div class="product-container">
            <h1 class="page-title"><span>Productos Destacados</span></h1>
            <div class="product-list">
                {foreach $products as $item}
                <div class="product-item {cycle values="col-1,col-2,col-3"} ">

                    <div class="image">
                        <a href="{$url_base}/producto/{$item.id}/{$item.url}"><img src="{$url_uploads}/product/large/{$item.image}" /></a>
                    </div>
                    <a class="name" href="{$url_base}/producto/{$item.id}/{$item.url}">{$item.name}</a>
                    {if $item.price}<div class="price">Bs. {$item.price}</div>{/if}
                </div>
                {/foreach}
            </div>
        </div>
        
    </div>
    <div class="clearfix"></div>
</div>
<script type="text/javascript">
    jQuery(window).load(function() {
        jQuery('div.product-list div.product-item div.image a img').each( function() {
            var _a = $(this) ;
            if ( _a.height() < 140 ) {
                _a.parent().css('top', ( 140 - _a.height() ) / 2 ) ;
            }
        } ) ;
    } ) ;
</script>